---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest update_cache=true
    - name: start nginx
      service:
          name: nginx
          state: started
